---
Description: EC2 Route Table Demo
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VPCId:
    Type: String
    Description: The VPC Id
  RouteTableName:
    Type: String
    Description: Name of the route table
Resources:
  MyVPC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCId
      Tags:
        - Key: Name
          Value: !Ref RouteTableName
